version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install -g serverless
      - cp serverless.yml.example serverless.yml
  build:
    commands:
      - serverless deploy
