version: 0.2

phases:
  install:
    commands:
    - cp serverless.yml.example serverless.yml
    - echo "Hola"
    - ls
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - mkdir -p target/dev
    - serverless deploy --package target/dev --stage dev -r us-east-2

artifacts:
  files:
  - target/dev/*
  - serverless.yml
  - deploy.sh
